server:
  port: 8084

spring:
  application:
    name: notification-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host: smtp.gmail.com
    port: 587
    username: priyanshu1singh11@gmail.com
    password: "uzxpivpxguurvpah"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
