server:
  port: 8085

spring:
  application:
    name: recharge-service
  datasource:
    url: jdbc:postgresql://localhost:5432/recharge_db
    username: root
    password: rootpassword
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
